use_frameworks!

platform :ios, '9.0'

target 'JKL_Example' do
  pod 'JKL', :path => '../'

  target 'JKL_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
